# Generated by Django 4.2.3 on 2023-07-03 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2023, 7, 3, 15, 26, 45, 92654))),
            ],
        ),
    ]
